### PR TITLE
dwarf: fix inline calls reporting 

### LINKED ISSUE #94: Symbolization of C inlined functions seems wrong
From https://github.com/stealthrocket/wasm-benchmarks/blob/main/c/main.c

image

`isAbs` doesn't call anything; the caller of `appendCleanPath` should be `joinPath`

### PR DESCRIPTION
**Pull request by pelletier**
Finally implement the original TODO of checking whether the PC being symbolized actually belong to the inline function to add to locations instead of adding all functions inlined in the caller, regardless of location. Also, correctly classify whether a location is the result of an inline call.

The rust test is updated for the same reason.

Also make sure tests are compiled with -g.

Fixes #94

### CODE REVIEW

File: dwarf.go [hunk 1]
```diff
@@ -308,20 +308,34 @@ func (d *dwarfmapper) Locations(fn experimental.InternalFunction, pc experimenta
...
+			}
+			found := false
+			for _, x := range ranges {
+				if x[0] <= offset && offset <= x[1] {
+					found = true
+				}
+			}
+			if !found {
+				continue
+			}
```
Comment (achille-roussel) [inline dwarf.go:337]: Whenever I write this kind of control flow I usually choose to move the loop into a function returning a boolean so I can get rid of the boolean value and have code that looks like this:
```go
if !rangesContainOffset(ranges, offset) {
    continue
}
```

**Review by achille-roussel — APPROVED** [review]
👏

File: dwarf.go (hunk 1 above)
Comment (pelletier) [reply dwarf.go]: Pushed on this branch a commit I was working on in parallel. I started moving some of the dwarf information gathering to when the dwarf section is initially parsed. As a result, it does fix this feedback. I'll push the rest in a separate PR.
